SELECT * FROM public."Customer";
-- Compare the average purchase amounts between Standard and Express shipping
SELECT shipping_type, ROUND(AVG("purchase_amount_(usd)"), 2) as avg_purchase_amount
FROM public."Customer"
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

select * from public."Customer";
--what is the total revenue generated by male vs female customers?
select gender,sum("purchase_amount_(usd)") as revenue
from public."Customer"
group by gender;
--which customer used a discount  but still spent more than average purchase_amount
WITH avg_val AS (
    SELECT AVG("purchase_amount_(usd)") AS avg_purchase
    FROM public."Customer"
)
select c.customer_id,c."purchase_amount_(usd)"
from public."Customer" c, avg_val
 where c.discount_applied='Yes' and c."purchase_amount_(usd)">=avg_val.avg_purchase ;
 --which are the top 5 products with the highest average review rating?
 select item_purchased,round(avg("review_rating"))as "Average Product Rating"
 from public."Customer"
 group by item_purchased
 order by avg(review_rating) desc 
 limit 5;
 --do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
 select subscription_status,count(customer_id)as total_customers,round(avg("purchase_amount_(usd)")) as avg_spend,
 round(sum("purchase_amount_(usd)")) as total_revenue
 from public."Customer"
 group by subscription_status
 order by total_revenue,avg_spend desc;
 --which 5 products have the highest percentage of purchases with discounts applied?
 select item_purchased,
 round(sum(case when discount_applied='Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
 from public."Customer"
 group by item_purchased
 order by discount_rate desc
 limit 5;
 --segemnt customers into new,returning and loyal based on their total
 --number of previous purchases and show the count of each segment
with customer_type as (
    select
        customer_id,
        previous_purchases,
        case
            when previous_purchases = 1 then 'New'
            when previous_purchases between 2 and 10 then 'Returning'
            else 'Loyal'
        end as customer_segment
    from public."Customer"
)
select
    customer_segment,
    count(*) as "Number of Customers"
from customer_type
group by customer_segment;

--what are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT("customer_id") AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT("customer_id") DESC
        ) AS item_rank
    FROM public."Customer"
    GROUP BY category, item_purchased
)
SELECT *
FROM item_counts;
--Are customers who are repeat buyers (more than 5 previous purchases) aslo likely to subscribe?
select subscription_status, count(customer_id)as repeat_buyers
from public."Customer"
where previous_purchases>5
group by subscription_status
--what is the revenue contribution of each age groups?
SELECT age,
       SUM(purchase_amount_usd) AS total_revenue,
       ROUND(AVG(purchase_amount_usd), 2) AS avg_spend
FROM public."Customer"
GROUP BY age
ORDER BY total_revenue DESC;





 
